name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.0
  - pybind11
  - setuptools
  - wheel
  - pytest
  - pytest-html
  - mpi4py=3.1.5
  - cython=0.29.36
  - h5py
  - pyyaml
  - parmetis
  - ptscotch
  - sphinx
  - sphinx-rtd-theme
  - sphinx-tabs
  - gcc_linux-64  # Provides gcc for Conda environment
  - gxx_linux-64  # Provides g++ for Conda environment
  - openmpi       # Ensures MPI implementation
  - jupyterlab    # For Binder notebook interface
